context:
  name: rustac
  version: "0.9.5"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/rustac-${{ version }}.tar.gz
  sha256: 775db537741cd1644edf2e411ebd0197f0f39f571311de1b6b96dba786090f93

build:
  number: 0
  python:
    entry_points:
      - rustac = rustac:main
    version_independent: true
  script:
    - if: win # work around long path problem, https://github.com/conda-forge/staged-recipes/commit/d86e4bb10154fc3833cae054e197ea2d7119dac7
      then: |
        set CARGO_HOME=C:\.cargo
        set MATURIN_PEP517_ARGS="--features=pyo3/abi3-py311,duckdb-bundled"
        md %CARGO_HOME%
      else: |
        export MATURIN_PEP517_ARGS="--features=pyo3/abi3-py311,duckdb-bundled,openssl-vendored"
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip:
    - not (match(python, python_min ~ ".*") and is_abi3)

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }} # needed to compile libduckdb-sys
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
    - make # needed to compile openssl-sys
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - maturin >=1.7,<2.0
        - python
  host:
    - maturin >=1.7,<2.0
    - pip
    - python ${{ python_min }}.*
    - if: is_abi3
      then:
        - python-abi3 ${{ python_min }}.*
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - rustac
      pip_check: true
      python_version: ["${{ python_min ~ '.*' }}"]
  - script:
      - rustac --help
      # NOTE: we must manually set SP_DIR since it is not set.
      # Can be removed once https://github.com/prefix-dev/rattler-build/issues/1733 is fixed.
      - if: unix and is_abi3
        then:
          - export SP_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
          - abi3audit $SP_DIR/rustac/rustac.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
      - if: win and is_abi3
        then:
          - set "SP_DIR=%PREFIX%\\Lib\\site-packages"
          - abi3audit %SP_DIR%\\rustac\\rustac.pyd -s -v --assume-minimum-abi3 ${{ python_min }}
    requirements:
      run:
        - abi3audit

about:
  homepage: https://stac-utils.github.io/rustac-py
  repository: https://github.com/stac-utils/rustac-py
  summary: A no-dependency Python package for STAC, using Rust under the hood.
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - gadomski
    - weiji14
